version: '3.7'

volumes:
  dependencies:

services:
  front:
    build:
      context: .
      dockerfile: ./docker-dev.dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    tty: true

  solver:
    build:
      context: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server:/app
      - dependencies:/app/node_modules
    tty: true
    environment:
      - PORT_NUMBER=4000
