version: '3.7'

services:
  front:
    build:
      context: .
      dockerfile: ./docker-dev.dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    tty: true

  solver:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000
    tty: true
    environment:
      - PORT_NUMBER=4000
